version: '2'
services:
  mongo:
    image: mongo:3.4.1
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - mongo
